/**
 * Ingest synthetic CRM data into TigerGraph GraphRAG.
 *
 * Flow:
 *   1. Read data/crm/chunks.jsonl (generated by generate-crm.ts)
 *   2. Convert to TigerGraph doc format { doc_id, doc_type, content }
 *   3. Write to data/crm_ingest.jsonl
 *   4. docker cp into TigerGraph container
 *   5. RUN LOADING JOB via gsql CLI inside container
 *   6. POST /{graph}/graphrag/forceupdate → TigerGraph chunks + embeds async
 *
 * After this runs, the CRM data is queryable via the same graphrag/search
 * endpoint used by the existing pipeline. The pipeline already does
 * vector search → graph traversal using IS_AFTER edges between chunks
 * of the same document — which maps to our CRM entity relationships.
 */

import 'dotenv/config';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';
import { config } from 'dotenv';

const __dirname = dirname(fileURLToPath(import.meta.url));
config({ path: join(__dirname, '../.env'), override: true });

const CHUNKS_PATH   = join(__dirname, '../data/crm/chunks.jsonl');
const JSONL_PATH    = join(__dirname, '../data/crm_ingest.jsonl');
const TG_URL        = process.env.TG_GRAPHRAG_URL ?? 'http://localhost:8000';
const GRAPH_NAME    = process.env.TG_GRAPH_NAME   ?? 'MyGraph';
const TG_USER       = process.env.TG_USERNAME      ?? 'tigergraph';
const TG_PASS       = process.env.TG_PASSWORD      ?? 'tigergraph';
const AUTH          = Buffer.from(`${TG_USER}:${TG_PASS}`).toString('base64');
const TG_CONTAINER  = 'tg-graphrag-db';
const BATCH_SIZE    = 500; // forceupdate batches

// ── helpers ───────────────────────────────────────────────────────────────────

async function tgPost(path: string, body: Record<string, unknown>): Promise<Record<string, unknown>> {
  const res = await fetch(`${TG_URL}/${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Basic ${AUTH}` },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`POST ${path} → ${res.status}: ${text.slice(0, 400)}`);
  try { return JSON.parse(text) as Record<string, unknown>; } catch { return { raw: text }; }
}

function run(cmd: string, input?: string): string {
  try {
    return execSync(cmd, {
      input,
      encoding: 'utf8',
      stdio: input !== undefined ? ['pipe', 'pipe', 'pipe'] : ['inherit', 'pipe', 'pipe'],
      timeout: 300_000,
    });
  } catch (e) {
    const out = ((e as { stdout?: string }).stdout ?? '') + ((e as { stderr?: string }).stderr ?? '');
    if (/loading job|background/i.test(out)) return out; // expected TG output
    throw new Error(`Command failed: ${(e as Error).message}\n${out.slice(0, 500)}`);
  }
}

// ── Step 1: Build JSONL ──────────────────────────────────────────────────────

function buildJsonl(): string[] {
  console.log('\n[1/4] Reading CRM chunks and building ingest JSONL…');

  if (!existsSync(CHUNKS_PATH)) {
    throw new Error(`CRM chunks not found at ${CHUNKS_PATH}. Run: npx tsx scripts/generate-crm.ts`);
  }

  const rawLines = readFileSync(CHUNKS_PATH, 'utf8').trim().split('\n');
  interface CrmChunk { id: string; source_type: string; source_id: string; text: string; metadata: Record<string,unknown> }

  // Group chunks by source_id — each entity becomes one "document"
  // Sequential chunks of the same entity get IS_AFTER edges automatically
  const docMap = new Map<string, string[]>();
  for (const line of rawLines) {
    const chunk = JSON.parse(line) as CrmChunk;
    const docId = `crm_${chunk.source_type}_${chunk.source_id}`;
    if (!docMap.has(docId)) docMap.set(docId, []);
    docMap.get(docId)!.push(chunk.text);
  }

  // Each document = all chunks of one CRM entity joined
  // TigerGraph will re-chunk and embed them
  const jsonlLines: string[] = [];
  for (const [docId, texts] of docMap.entries()) {
    const content = texts.join('\n\n---\n\n');
    // Truncate to 50k chars per document (TG GSQL string limit)
    jsonlLines.push(JSON.stringify({
      doc_id: docId,
      doc_type: 'characters',
      content: content.slice(0, 50_000),
    }));
  }

  writeFileSync(JSONL_PATH, jsonlLines.join('\n') + '\n', 'utf8');
  const totalChars = jsonlLines.reduce((s, l) => s + l.length, 0);
  console.log(`      ✓ ${jsonlLines.length} documents → data/crm_ingest.jsonl`);
  console.log(`        (~${(totalChars / 4_000_000).toFixed(2)}M tokens)`);
  return jsonlLines;
}

// ── Step 2: docker cp ─────────────────────────────────────────────────────────

function copyToContainer(): void {
  console.log(`\n[2/4] Copying JSONL into container "${TG_CONTAINER}"…`);
  run(`docker cp "${JSONL_PATH}" ${TG_CONTAINER}:/tmp/crm_ingest.jsonl`);
  console.log('      ✓ /tmp/crm_ingest.jsonl ready inside container.');
}

// ── Step 3: Run loading job ──────────────────────────────────────────────────

function runLoadingJob(): void {
  console.log('\n[3/4] Running GSQL loading job inside TigerGraph container…');

  const script = `USE GRAPH ${GRAPH_NAME}\nRUN LOADING JOB load_documents_content_json USING DocumentContent="/tmp/crm_ingest.jsonl"`;
  const dockerCmd = `docker exec -i ${TG_CONTAINER} /home/tigergraph/tigergraph/app/4.2.2/cmd/gsql -u ${TG_USER} -p ${TG_PASS}`;

  console.log('      Running loading job (30-120 seconds)…');
  const out = run(dockerCmd, script);

  const meaningful = out.split('\n')
    .filter(l => l.trim() && !/^GSQL>|^>/.test(l.trim()))
    .slice(0, 6)
    .join('\n      ');
  console.log(`      Output:\n      ${meaningful}`);
  console.log('      ✓ Loading job complete.');
}

// ── Step 4: Force update (chunk + embed) ─────────────────────────────────────

async function forceUpdate(docIds: string[]): Promise<void> {
  console.log(`\n[4/4] Triggering TigerGraph ECC to chunk + embed ${docIds.length} documents…`);
  console.log('      (This runs async inside TigerGraph — takes 5-30 min for full dataset)');

  // Send in batches to avoid request size limits
  let done = 0;
  for (let i = 0; i < docIds.length; i += BATCH_SIZE) {
    const batch = docIds.slice(i, i + BATCH_SIZE);
    try {
      await tgPost(`${GRAPH_NAME}/graphrag/forceupdate`, { doc_ids: batch });
      done += batch.length;
      process.stdout.write(`\r      ✓ Submitted ${done}/${docIds.length} documents…`);
    } catch (err) {
      console.warn(`\n      ⚠ Batch ${i}-${i + BATCH_SIZE} failed: ${(err as Error).message.slice(0, 100)}`);
    }
    if (i + BATCH_SIZE < docIds.length) {
      await new Promise(r => setTimeout(r, 500));
    }
  }
  console.log(`\n      ✓ All ${done} documents submitted for embedding.`);
  console.log('      TigerGraph is now chunking + embedding in the background.');
  console.log('      Check status: GET /MyGraph/graphrag/status');
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log('═══════════════════════════════════════════════');
  console.log('  CRM → TigerGraph Ingest Pipeline');
  console.log('═══════════════════════════════════════════════');

  // Check Docker is running
  try {
    run('docker ps --filter name=tg-graphrag-db --format "{{.Names}}"');
  } catch {
    throw new Error('Docker not running or tg-graphrag-db container not found. Run: npm run tg:up');
  }

  const jsonlLines = buildJsonl();
  const docIds = jsonlLines.map(l => (JSON.parse(l) as { doc_id: string }).doc_id);

  copyToContainer();
  runLoadingJob();
  await forceUpdate(docIds);

  console.log('\n═══════════════════════════════════════════════');
  console.log('  ✅ CRM ingest complete!');
  console.log(`     ${docIds.length} documents loaded into TigerGraph`);
  console.log('');
  console.log('  Next steps:');
  console.log('  1. Wait 5-30 min for TigerGraph to finish embedding');
  console.log('  2. Run the CRM eval: npx tsx scripts/run-crm-eval.ts');
  console.log('═══════════════════════════════════════════════\n');
}

main().catch(err => { console.error('Fatal:', err.message); process.exit(1); });
