/**
 * Ingest Activity Logs into TigerGraph
 *
 * Reads data/activity_ingest.jsonl (generated by generate-activity-logs.ts)
 * and loads it into TigerGraph using the same pipeline as ingest-crm.ts:
 *   1. docker cp JSONL into container
 *   2. RUN LOADING JOB load_documents_content_json
 *   3. GET /graphrag/forceupdate  (triggers chunking + embedding)
 *
 * No schema changes. No eval pipeline changes. Same GSQL queries.
 */

import 'dotenv/config';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';
import { config } from 'dotenv';

const __dirname = dirname(fileURLToPath(import.meta.url));
config({ path: join(__dirname, '../.env'), override: true });

const JSONL_PATH    = join(__dirname, '../data/activity_ingest.jsonl');
const TG_URL        = process.env.TG_GRAPHRAG_URL ?? 'http://localhost:8000';
const GRAPH_NAME    = process.env.TG_GRAPH_NAME   ?? 'MyGraph';
const TG_USER       = process.env.TG_USERNAME      ?? 'tigergraph';
const TG_PASS       = process.env.TG_PASSWORD      ?? 'tigergraph';
const TG_CONTAINER  = 'tg-graphrag-db';
const AUTH          = Buffer.from(`${TG_USER}:${TG_PASS}`).toString('base64');

function run(cmd: string, input?: string): string {
  try {
    return execSync(cmd, {
      input,
      encoding: 'utf8',
      stdio: input !== undefined ? ['pipe','pipe','pipe'] : ['inherit','pipe','pipe'],
      timeout: 600_000,
    });
  } catch (e) {
    const out = ((e as { stdout?: string }).stdout ?? '') + ((e as { stderr?: string }).stderr ?? '');
    if (/loading job|background/i.test(out)) return out;
    throw new Error(`Command failed: ${(e as Error).message}\n${out.slice(0, 500)}`);
  }
}

async function tgGet(path: string): Promise<Record<string, unknown>> {
  const res = await fetch(`${TG_URL}/${path}`, {
    headers: { 'Authorization': `Basic ${AUTH}` },
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`GET ${path} → ${res.status}: ${text.slice(0, 400)}`);
  try { return JSON.parse(text) as Record<string, unknown>; } catch { return { raw: text }; }
}

async function main(): Promise<void> {
  console.log('═══════════════════════════════════════════════════════');
  console.log('  Activity Logs → TigerGraph Ingest');
  console.log('═══════════════════════════════════════════════════════');

  if (!existsSync(JSONL_PATH)) {
    throw new Error('data/activity_ingest.jsonl not found. Run first:\n  npx tsx scripts/generate-activity-logs.ts');
  }

  // Count docs
  const lines = readFileSync(JSONL_PATH, 'utf8').trim().split('\n');
  const totalChars = lines.reduce((s, l) => s + l.length, 0);
  console.log(`\n  Loaded ${lines.length.toLocaleString()} docs`);
  console.log(`  (~${(totalChars / 4_000_000).toFixed(1)}M tokens)\n`);

  // Step 1: docker cp
  console.log('[1/3] Copying JSONL into TigerGraph container…');
  try {
    run(`docker ps --filter name=${TG_CONTAINER} --format "{{.Names}}"`);
  } catch {
    throw new Error(`Container "${TG_CONTAINER}" not running. Start it with: npm run tg:up`);
  }
  run(`docker cp "${JSONL_PATH}" ${TG_CONTAINER}:/tmp/activity_ingest.jsonl`);
  console.log('      ✓ /tmp/activity_ingest.jsonl ready in container');

  // Step 2: GSQL loading job
  console.log('\n[2/3] Running GSQL loading job…');
  const script = `USE GRAPH ${GRAPH_NAME}\nRUN LOADING JOB load_documents_content_json USING DocumentContent="/tmp/activity_ingest.jsonl"`;
  const dockerCmd = `docker exec -i ${TG_CONTAINER} /home/tigergraph/tigergraph/app/4.2.2/cmd/gsql -u ${TG_USER} -p ${TG_PASS}`;
  const out = run(dockerCmd, script);
  const meaningful = out.split('\n').filter(l => l.trim() && !/^GSQL>|^>/.test(l.trim())).slice(0, 6).join('\n      ');
  console.log(`      Output:\n      ${meaningful}`);
  console.log('      ✓ Loading job complete');

  // Step 3: Force update (chunk + embed)
  console.log('\n[3/3] Triggering TigerGraph ECC to chunk + embed new docs…');
  try {
    const result = await tgGet(`${GRAPH_NAME}/graphrag/forceupdate`);
    console.log(`      ✓ Submitted: ${JSON.stringify(result)}`);
  } catch (err) {
    console.warn(`      ⚠ forceupdate: ${(err as Error).message.slice(0, 200)}`);
    console.warn('        (This is OK if TigerGraph is already processing — check status manually)');
  }

  console.log('\n═══════════════════════════════════════════════════════');
  console.log('  ✅ Activity log ingest complete!');
  console.log(`     ${lines.length.toLocaleString()} documents loaded`);
  console.log('');
  console.log('  TigerGraph is now embedding in the background.');
  console.log('  Check: GET /MyGraph/graphrag/status');
  console.log('');
  console.log('  Once done, update the UI badge:');
  console.log('  → 123M → 150M tokens in web/index.html + apps/web/src/main.tsx');
  console.log('═══════════════════════════════════════════════════════\n');
}

main().catch(err => { console.error('Fatal:', err.message); process.exit(1); });
